# Generated by Django 5.0.1 on 2026-07-06 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_agentpendingbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='marketplace.useragent'),
        ),
    ]
